//Products
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID';
export const GET_PRODUCT_BY_NAME = 'GET_PRODUCT_BY_NAME';
export const ADD_PRODUCT='ADD_PRODUCT';
export const MOD_PRODUCT='MOD_PRODUCT';
export const DEL_PRODUCT='DEL_PRODUCT';
export const CLEAR_PRODUCT_DETAILS = 'CLEAR_PRODUCT_DETAILS'
export const MOD_QUANTITY_LOCAL = 'MOD_QUANTITY_LOCAL';


//Shopping Cart
export const GET_SC_BY_ID="GET_SC_BY_ID"
export const PUT_SC="PUT_SC"
export const POST_SC="POST_SC"
export const ADD_PRODUCT_SC='ADD_PRODUCT_SC'
export const CLEAR_SC="CLEAR_SC"
export const CLEAR_CUSTOMER_ID="CLEAR_CUSTOMER_ID"
export const REMOVE_PRODUCT_SC= "REMOVE_PRODUCT_SC"
export const UPDATE_PRODUCT_QUANTITY_SC = "UPDATE_PRODUCT_QUANTITY_SC";
export const UPDATE_TOTAL= "UPDATE_TOTAL"



//Customers
export const GET_CUSTOMERS = 'GET_CUSTOMERS';
export const GET_CUSTOMER_BY_ID = 'GET_CUSTOMER_BY_ID';
export const GET_CUSTOMER_BY_EMAIL = 'GET_CUSTOMER_BY_ID';
export const ADD_CUSTOMER='ADD_CUSTOMER';
export const MOD_CUSTOMER='MOD_CUSTOMER';
export const DEL_CUSTOMER='DEL_CUSTOMER';
export const LOGIN_CUSTOMER='LOGIN_CUSTOMER'

//Order Detail
export const ADD_ORDER_DETAIL='ADD_ORDER_DETAIL';
export const GET_ORDER_DETAIL_BY_ID = 'GET_ORDER_DETAIL_BY_ID';

//Order
export const GET_ORDERS = 'GET_ORDERS';
export const GET_ORDER_BY_ID = 'GET_ORDER_BY_ID';
export const FILTER_CATEGORY = 'FILTER_CATEGORY';
export const RANGO_PRECIOS = 'RANGO_PRECIOS';
export const ORDER_PRECIO = 'ORDER_PRECIO';

// CATEGORY
export const GET_CATEGORY = 'GET_CATEGORY';
export const ADD_CATEGORY = 'ADD_CATEGORY';

//COMENT 
export const POST_COMMENT = 'POST_COMMENT';
export const GET_ALL_COMMENTS = 'GET_ALL_COMMENTS';


//Buy
export const GET_BUY = "GET_BUY";


export const LOAD_STOCK='LOAD_STOCK';
export const MOD_STOCK='MOD_STOCK';


